//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarFixed.DS.DM
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasicSubCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BasicSubCategory()
        {
            this.BasicSubCategoryRepairRefs = new HashSet<BasicSubCategoryRepairRef>();
            this.QuoteItemBasics = new HashSet<QuoteItemBasic>();
        }
    
        public int BasicSubCategoryID { get; set; }
        public int BasicCategoryID { get; set; }
        public int BasicSubCategoryGroupID { get; set; }
        public string Title { get; set; }
        public Nullable<bool> IsLinkedToRepairTime { get; set; }
        public Nullable<bool> IsLinkedToService { get; set; }
    
        public virtual BasicCategory BasicCategory { get; set; }
        public virtual BasicSubCategoryGroup BasicSubCategoryGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasicSubCategoryRepairRef> BasicSubCategoryRepairRefs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuoteItemBasic> QuoteItemBasics { get; set; }
    }
}
