//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarFixed.DS.DM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Garage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Garage()
        {
            this.CarFixedUsers = new HashSet<CarFixedUser>();
            this.GarageServices = new HashSet<GarageService>();
            this.Quotes = new HashSet<Quote>();
            this.QuoteGarageOptions = new HashSet<QuoteGarageOption>();
        }
    
        public int GarageID { get; set; }
        public string Name { get; set; }
        public System.DateTime DateAdded { get; set; }
        public string GarageRef { get; set; }
        public Nullable<int> AddressID { get; set; }
        public Nullable<bool> IsVatRegistered { get; set; }
        public string VatNumber { get; set; }
        public string Description { get; set; }
        public Nullable<int> NoOfRamps { get; set; }
        public int StatusID { get; set; }
    
        public virtual Address Address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarFixedUser> CarFixedUsers { get; set; }
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GarageService> GarageServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Quote> Quotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuoteGarageOption> QuoteGarageOptions { get; set; }
    }
}
