//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarFixed.DS.DM
{
    using System;
    using System.Collections.Generic;
    
    public partial class GarageService
    {
        public int GarageServiceID { get; set; }
        public int GarageID { get; set; }
        public int BasicCategoryID { get; set; }
    
        public virtual BasicCategory BasicCategory { get; set; }
        public virtual Garage Garage { get; set; }
    }
}
