//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarFixed.DS.DM
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuoteItemBasic
    {
        public int QuoteItemBasicID { get; set; }
        public int QuoteID { get; set; }
        public int BasicSubCategoryID { get; set; }
        public System.DateTime DateAdded { get; set; }
        public string AdditionalInfo { get; set; }
    
        public virtual Quote Quote { get; set; }
        public virtual BasicSubCategory BasicSubCategory { get; set; }
    }
}
