//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarFixed.DS.DM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quote
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Quote()
        {
            this.QuoteItemAdvRepairs = new HashSet<QuoteItemAdvRepair>();
            this.QuoteItemAdvServices = new HashSet<QuoteItemAdvService>();
            this.QuoteItemBasics = new HashSet<QuoteItemBasic>();
            this.QuoteGarageOptions = new HashSet<QuoteGarageOption>();
        }
    
        public int QuoteID { get; set; }
        public int VehicleID { get; set; }
        public string AdditionalInfo { get; set; }
        public int QuoteUrgencyID { get; set; }
        public System.DateTime DateAdded { get; set; }
        public Nullable<decimal> EstimatedHours { get; set; }
        public Nullable<int> EstimatedMinutes { get; set; }
        public Nullable<int> GarageID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> QuoteEmailFrequencyID { get; set; }
    
        public virtual QuoteUrgency QuoteUrgency { get; set; }
        public virtual Vehicle Vehicle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuoteItemAdvRepair> QuoteItemAdvRepairs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuoteItemAdvService> QuoteItemAdvServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuoteItemBasic> QuoteItemBasics { get; set; }
        public virtual Garage Garage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuoteGarageOption> QuoteGarageOptions { get; set; }
    }
}
