//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarFixed.DS.DM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicle()
        {
            this.Quotes = new HashSet<Quote>();
        }
    
        public int VehicleID { get; set; }
        public int CarFixedUserID { get; set; }
        public string VRM { get; set; }
        public int GCodeID { get; set; }
        public string Manufacturer { get; set; }
        public string Model { get; set; }
        public Nullable<int> Year { get; set; }
        public string FuelType { get; set; }
        public Nullable<int> LastKnownMileage { get; set; }
        public Nullable<bool> HasServicePlan { get; set; }
        public Nullable<System.DateTime> ServicePlanExpiryDate { get; set; }
        public Nullable<bool> HasWarranty { get; set; }
        public Nullable<System.DateTime> WarrantyExpiryDate { get; set; }
        public System.DateTime DateAdded { get; set; }
        public bool IsDisplayed { get; set; }
    
        public virtual CarFixedUser CarFixedUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Quote> Quotes { get; set; }
    }
}
